WFCD/WFinfo

- README.md
also link image for post so it opens out to the forums instead of another tab for the image
> cleanups for readability

- WFInfoCS/Data.cs
- WFInfoCS/LogCapture.cs
- WFInfoCS/Settings.xaml
- WFInfoCS/WFInfoCS.csproj
- WFInfoCS/packages.config
re-writing of the Data.vb and log watcher.vb class in C#
> Start rework on Data/LogCapture

- WFInfo/Data.vb
> Wiki parsing hotfix

- .gitignore
- Launcher/Launcher.csproj
- Launcher/packages.config
- WFInfo/MainWindow.xaml.cs
- WFInfo/Settings.xaml
- WFInfo/WFInfo.csproj
Test to see if pull requests work
> Test pullrequest

- WFInfo/EquipmentWindow.cs
- WFInfo/EquipmentWindow.xaml
- WFInfo/MainWindow.xaml.cs
- WFInfo/RelicsWindow.cs
- WFInfo/RelicsWindow.xaml
- WFInfo/TreeNode.cs
Plus some other fun stuff like +/- buttons for relics, and single click expand
> Force Search Matches to be Always Visible

- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Settings.xaml.cs
No longer hard coded, users that want to remove it can, still defaulted with it on.
> Changed the ad section to be customizable 

- WFInfo/App.xaml.cs
- WFInfo/Main.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/UpdateDialogue.xaml
- WFInfo/UpdateDialogue.xaml.cs
- WFInfo/WFInfo.csproj
Loads all release notes between current version and new version
Matches current ui style
> Created Custom Update Window

- WFInfo/LowLevelListener.cs
- WFInfo/Main.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Settings.xaml
- WFInfo/Settings.xaml.cs
Key Name no longer uses Key Enum
Activation is disabled while selection a key
If Key can't be loaded from json, defaults to snapshot
Misc Key naming improvements (English Only)
Fixed issue with Alt being caught as Key.System
Need to confirm with non-US keyboards
> Various Improvements to Key Selection

- WFInfo/CustomEntrypoint.cs
- WFInfo/Data.cs
- WFInfo/InitialDialogue.xaml.cs
- WFInfo/LogCapture.cs
- WFInfo/Main.cs
- WFInfo/MainWindow.xaml
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/TreeNode.cs
- WFInfo/UpdateDialogue.xaml
- WFInfo/UpdateDialogue.xaml.cs
- WFInfo/WFInfo.csproj
- WFInfo/WelcomeDialogue.xaml
- WFInfo/WelcomeDialogue.xaml.cs
- WFInfo/errorDialogue.xaml
- WFInfo/initialDialogue.xaml
Added Exception Handling to all threads to alert the user when something goes awry
Also added some exception handling to dll download process
Changed initial load to display a window to inform the user that the app is active
Modified tessdata download to occur during database downloads
Changed initial user welcome to match WFInfo style
> Improved User Experience

- WFInfo/App.xaml
- WFInfo/App.xaml.cs
- WFInfo/MainWindow.xaml.cs
When main window closes, shut down program. Preventing most, if not all ghost processes.
> Shut down program on main window exit

- WFInfo/App.xaml.cs
- WFInfo/InitialDialogue.xaml.cs
- WFInfo/LowLevelListener.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/TreeNode.cs
Changes to treeview to prevent w10 errors
> Changes to prevent lag on exit

- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Settings.xaml.cs
Developed a mode that detects scaling at very high accuracy with little performance draw
1080p sees 50ms to 200ms extra latency
4K sees 100ms to 300ms
Currently disabled unless "CuttingEdge" is enabled in settings
> Automatic Scaling Detection

- WFInfo/Main.cs
Added the ability to use snapit with debug disabled.
> Fixed the inability to use snap it without debug enabled.

- WFInfo/Data.cs
- WFInfo/Ocr.cs
- WFInfo/Overlay.xaml.cs
- WFInfo/RewardWindow.xaml
- WFInfo/RewardWindow.xaml.cs
Forma now only shows name, no plat images or anything else. In future any item with 0 ducats will only display name.
> Changes to displaying forma

- WFInfo/Data.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Overlay.xaml
- WFInfo/Overlay.xaml.cs
- WFInfo/Settings.xaml.cs
- WFInfo/TreeNode.cs
Highlights for owned, plat and ducats
> Implementing best rewart highlighting

- WFInfo/Data.cs
- WFInfo/Ocr.cs
Minimize errors when opening Requiem relics
> Implement the "ignored_items" key from the json

- WFInfo/Data.cs
- WFInfo/Ocr.cs
Before still relied on old scaling based method.
> Changed to smart detection on scale

- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Settings.xaml
- WFInfo/Settings.xaml.cs
Scaling values are no longer there. Also fixed ducats showing up in clipboard
> Changed default settings

- WFInfo/Ocr.cs
Program should no longer get stuck on processing
> Fix to getting stuck, ducats for non-vaulted stuff

- docs/index.html
Adjusted the website with up to date info and a wfm tutorial
> Updated website to 9.3

- WFInfo/Overlay.xaml.cs
- docs/index.html
Fixed website spelling + efficiency parsing now uses main.culture.
> Two small bugfixes

- WFInfo/Data.cs
- WFInfo/Main.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/PlusOne.xaml
- WFInfo/PlusOne.xaml.cs
- WFInfo/Properties/AssemblyInfo.cs
- WFInfo/Settings.xaml.cs
- WFInfo/TreeNode.cs
- WFInfo/WFInfo.csproj
- WFInfo/Win32.cs
- WFInfo/app.manifest
- WFInfo/errorDialogue.xaml.cs
- docs/index.html
Fixed some spelling mistakes
Added culture parsing to efficiency so it will properly show now.
Fixed issue where multiple web sockets where being opened at once resulting in the status being quickly switched back and forth.
Fixed equipment tree closing the parent node whenever adding an item.
Fixed an error message being to long and cut off in the status bar.
Fixed dpi not being properly gotten resulting in anything but 100% dpi resulting in a mess.
> Update to 9.3.1

- WFInfo/Login.xaml
- WFInfo/Login.xaml.cs
Showing the error message when login to WFM under the password box instead of only the status
https://i.imgur.com/siV9zpr.png
> Showing Login Error message

- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Properties/AssemblyInfo.cs
- WFInfo/Settings.xaml
- WFInfo/Settings.xaml.cs
round 2 pr
a continuation of: https://github.com/WFCD/WFinfo/pull/136
Cloned the most recent master, and copied in my changes over the top.
> Overlay sliders

- WFInfo/Main.cs
Fixed some upload errors (thx Dimon for warning me)
> PR #141 part 2 - adding a fullscreen popup error

- WFInfo/CustomEntrypoint.cs
- WFInfo/Data.cs
- WFInfo/Main.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Settings.xaml
- WFInfo/Settings.xaml.cs
Created a language selection combo in the settings window.
TesseractEngine is Dispose and regenerated based on language selection.
I changed from creating a market item from filterAllJSON to an API call. This may not be efficient, but i developed it this way to support other languages ​​dynamically.
Legacy theme calculations changed.
I checked the normal operation in English and Korean, but I commented that a check is necessary.
And when the master branch was pulled, an error occurred because the Spawn Full Screen Reminder method was not implemented. Although it was temporarily processed, it needs to be corrected because i do not know what kind of screen it is intended for.
> Wfinfo locale

- WFInfo/errorDialogue.xaml.cs
Undid zip name changes due to it breaking the unzipping process
> undid zip name changes

- WFInfo/CustomEntrypoint.cs
- WFInfo/MainWindow.xaml.cs
- WFInfo/Ocr.cs
- WFInfo/Properties/AssemblyInfo.cs
- WFInfo/WFInfo.csproj
> Added logging for Windows version, .net version and C++ version. Added check for Admin mode

- WFInfo/Data.cs
Blabla switch to CDN (dont merge until links are updated)
> Use remote CDN instead of Google Sheets

- WFInfo/Data.cs
Fix WFM status websocket not working. This was caused in #239 as not specifying SslProtocol apparently defaults it to a now-deprecated protocol. Setting it to None allows negotiation
Fix WFM commands being treated as logged out. Commands executed while not logged in (including failed login attempts) apparently set the cookie to a non-logged-in JWT. That cookie took precedence over the header. Fixed by telling HttpClientHandler to not use cookies.
---
1. Open browser of your WFM profile (preferrably not logged in)
2. Log in to WFM inside WFInfo
3. Try changing status, reload webpage to check if it changed or not
Option 1:
1. Intentionally fail a login attempt (wrong email, wrong password)
2. Perform a successful login attempt
3. Attempt to create an order through list-it (pick random item …
> Fix WFM Integration issues

- WFInfo/Ocr.cs
Fix rare issue where the relic reward selection border would sometimes be included in the crop and mess up the OCR.
---
1. Scan a problematic image using reward screen scanning (test image provided below)
2. Compare resulting items to actual items
---
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**
> Add heuristic to solve selection border issue

- WFInfo/errorDialogue.xaml.cs
> Reduce upload limit back to 10 MB

- WFInfo/Properties/AssemblyInfo.cs
- WFInfo/Settings/ThemeAdjuster.xaml.cs
- WFInfo/WFInfo.csproj
- WFInfo/verifyCount.xaml.cs
Slowly preparing to sunset DotNetZip...
> Upgrade libs, bump version, clean imports
