WFCD/WFinfo

WFInfo/Data.cs, WFInfo/EquipmentWindow.cs
Now if a part doesn't have market data, it gets removed from the window
Also, if a eqmt doesn't have a single part with data, it also gets removed
=> Old Eqmt Data caused Blank Eqmt/Parts to show in Eqmt Window

WFInfo/MainWindow.xaml.cs, WFInfo/Ocr.cs, WFInfo/Settings.xaml.cs
Ability to now toggle if you want clipboard to also show vaulted items. Note, this is only enabled in the settings menu as this is not intended to be used by the masses. It's recommended to alter the ad section as well if you're enabling this to explain what the V means.
=> Show vaulted in clipboard

WFInfo/Ocr.cs, WFInfo/WFInfo.csproj, WFInfo/fullscreenReminder.xaml, WFInfo/fullscreenReminder.xaml.cs
When the OCR triggers, if Warframe runs in fullscreen, it will popup a window to inform the user it will not work as intended.
The popup have 2 buttons : 
* "Disable Overlay" - will open the settings, letting the user choose by himself which mode he wants
* "Change game display" - just close the window
note : this window only triggers on the FIRST activation after the launch IF the display mode is on overlay
=> Added a Fullscreen error popup

WFInfo/RelicsWindow.cs, WFInfo/RelicsWindow.xaml, WFInfo/TreeNode.cs
Added intact & Radiant sum per relic era of unvaulted relics so you can easily see what relics to farm for best efficency
fixed sorting of relics to account for names like 
A1 A11 A2 -> now A1 A2 A11
=> Fixed Relic sort & added Relic Era plat sums

WFInfo/Ocr.cs, WFInfo/verifyCount.xaml.cs
closed \#180 - Added exception for Kavasa Prime Kubrow Collar on item count save.
Added logging for SnapIt item counting, mainly on count save.
---
1. Use SnapIt with item counting enabled in an area that contains the item "Kavasa Prime Kubrow Collar Blueprint"
2. Select "Save Count" in the count verification dialogue box 
3. (Before fix): WFInfo crashes and item counts are not saved. (After fix): Doesn't crash and successfully saves the item count.
---
Bug fix on line 52 of WFInfo/verifyCount.xaml.cs
Crash tolerance is on line 55-63. 
The rest of the changes are for logging
- Does this pr include updated data files in a separate commit that can be reverted for a …
=> Kubrow fix

WFInfo/MainWindow.xaml.cs, WFInfo/Ocr.cs, WFInfo/Settings.xaml.cs
Horizontal pad for detecting item name overlap in SnapIt removed by default, but can be modified in settings. This is in response to an issue reported by Corgo#6755 on Discord, where certain items (Inaros Prime Chassis Blueprint, Ivara Prime Chassis Blueprint) being next to eachother would cause a bounds overlap on 3440x1440 resolution, which also caused a crash on attempted item count save in said scenario. Also updated the number detection box to adjust for this change, and added settings to enable manual adjustment to said box width.
All new settings are exclusively in file, as they should only be needed to adjust for other issues
---
1. Use SnapIt, with item counting enabled if you want to check the adjustment to the number detection box.
2. Check the resulting SnapItImageBounds image …
=> SnapIt Horizontal bounds cleanup and settings

WFInfo/Ocr.cs
Mastered items no longer display with the unowned color in the reward screen.
---
1. I marked an equipment as mastered
2. Used a full-screenshot to test reward screen parsing
3. The mastered reward showed up with the unowned color.
---
Test SS:
Before fix:
After fix:
- Is is a bug fix, feature request, or enhancement? **[Bug fix]**
=> Made mastered items not show up as unowned.

WFInfo/Ocr.cs
Sped up pixel get and set times for filtering step of Snap It and most of Master It, as suggested by CruleD#8893 on discord ([reference implementation](https://github.com/CruleD/Warframe-ReBa-Farmer/blob/2745fed6a4847659608e19a144fe71b86d256c02/Warframe%20ReBa%20Farmer/Module_RelicScanner.cs#L170))
---
1. Use Snap It or Master It. Debug mode and a few runs per test image recommended to get a good time comparison
---
For the following test image, time went from around 2500ms to around 650 ms. (snap it, whole image due to debug mode, count item disabled)
For the following test image, time went from around 1600ms to around 1400ms (mastered scan)
For the following test image, time went from **around 12700ms (!!!)** to around 1500ms (mastered scan)
- Does this contain a new dependency? …
=> Snap it and Master it speedup

WFInfo/Data.cs, WFInfo/Ocr.cs
- Cleaned up log and debug images for Master IT
- Added additional validity checks to Master It
- Added extra spacing between characters in the image being OCR'd for better results at slightly lower resolution (tested for 1080p)
- Made amount of rows checked before skipping to below the current results to be relative to height rather than a set amount, this fixes Deth Machine Rifle Prime preventing detecting of all other items on the same row.
---
1. Use master it on an image with one of the listed issues
---
Here's an example image where the additional spacing between characters makes the item name readable: https://kintonhiryuu.live/screenshots/kinton/u/wL3A6Y.jpg
Here's an image where Deth Machine Rifle Prime previously screwed up the detection of Dethcube Prime, but should work with …
=> Mastered fixes 1

WFInfo/MainWindow.xaml.cs, WFInfo/Ocr.cs, WFInfo/Settings.xaml, WFInfo/Settings.xaml.cs
- Fixed FullScreenShot debug image missing timestamp in name
- Fixed status displaying snap-it processing as finished after filtering instead of after actual snap-it processing.
- Added option to multithread snap-it for a siginificant speed improvement.
- When multithreaded snap-it is enabled, also adds white line below every row of text to solve issue of letters/words on different rows fusing together according to the OCR in certain circumstances. 
- Added proper combine order logic when piecing together item names, rather than just relying on the OCR doing it in the right order.
**NOTE**: multithreaded snap-it is currently turned off by default, you may want to change that. 
The splitting of the image for the multithreading is based on density of black pixels on each row and column, …
=> Multithreaded snap-it

WFInfo/RewardWindow.xaml.cs
Fixed the Window mode relic reward display only being able to show mastery status on the first item
---
1. Set the rewards display setting to Window
2. Scan reward screen containing an item marked as mastered in WFInfo in slot 2, 3 or 4
---
It's literally 3 lines, just read it
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**
=> Fixed WIndow mode only having mastery checkmark in first slot

WFInfo/TreeNode.cs
Currently, when you add, remove, or master items on the equipment window it refreshes the treeview which often causes everything to scroll randomly.
This fix prevents the whole treeview from refreshing. Counts seem to update fine without it.
If you're in "Owned" or related sort modes, it doesn't automatically resort, but that would probably be annoying (and doesn't appear to happen in current master anyway)
---
1. Open equipment view
2. Open all four top categories
3. Open an item in each category
4. Scroll halfway down, then add one to an item
5. The treeview scrolls as the Warframe category closes and reopens
---
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Is is a bug fix, feature request, or enhancement? …
=> Prevent equipment window scrolling on change

WFInfo/Data.cs, WFInfo/MainWindow.xaml.cs, WFInfo/Services/EncryptedDataService.cs, WFInfo/WFInfo.csproj
This swaps to using the ASP.NET Core [data protection api](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0) to store credentials.
On Windows, this will encrypt at rest using the user account to encrypt.
---
- Does this contain a new dependency? **Yes**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Have I run the linter? **Yes**
- Is is a bug fix, feature request, or enhancement? **Enhancement**
=> Store JWT using Windows DPAPI

Launcher/Launcher.csproj, WFInfo/Settings/SettingsWindow.xaml, WFInfo/Templates/Styles.xaml, WFInfo/WFInfo.csproj
* Upgraded libs including Foly and AutoUpdater that is supposed to improve DPI scaling and autoupdate permission error handling
* Adjusted style for Locale dropdown to actually be visible on black themed Windows
---
1. Click settings
2. Look at dropdown, try to select any value in dropdown, look at any style discrepancies
- Does this contain a new dependency? **No** (but versions go updated!)
- Does this introduce opinionated data formatting or manual data entry? **Maybe**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **Yes**
- Have I run the linter? **Yes**
- Is is a bug fix, feature request, or enhancement? **Bug Fix & Maintenance**
=> Upgrade libs, adjust locale dropdown style

WFInfo/Data.cs, WFInfo/SearchIt.xaml.cs
The recent JWT cookie length check for data sending prevented a login from completing which means the check will always fail as the full login cookie could never be set in a catch 22.
- I 100% just make up the number 300 out of looking at what the cookie length was when I loaded the page after deleing the cookie to sign myself out.  A total guess if this length is reasonable for all users or if the original not null check should still be used for "available" while 500 length should be used for "logged in"
=> Fixes warframe.market cookie status confusion between login / available

docs/index.html
- clean up snap-it references to use the same spelling and punctuation
- also update matomo site (it was set back up a while ago, forgot to give the new id) 
---
open https://wfinfo.warframestat.us
---
- Is is a bug fix, feature request, or enhancement? **[Docs]**
=> docs: make snap-it more consistently named in docs

WFInfo/CustomEntrypoint.cs, WFInfo/Data.cs, WFInfo/Services/TesseractService.cs, WFInfo/UpdateDialogue.xaml.cs
* No longer print JWT poll details (every 1 minute). It will now only print when Login happens or in case of errors
* Proxy support that was partially borrowed from #236 . To use proxy set env variable `http_proxy` in Windows settings. Proxy only needed for power users anyway.
* Some code cleanup/refactoring around generic factory for webclient (for any future use)
=> Proxy support, refactoring, less verbose logs

WFInfo/Ocr.cs, WFInfo/Settings/SettingsWindow.xaml
Disable snapit count feature because discord is countless crash screens.
Feature doesn't work so will be rewritten in the future.
=> Disable snapit count checks temporarily

WFInfo/Data.cs
Default statistics in `LoadMarketItem` if the item doesn't have any yet.
Remove `Blueprint` from WFM item name to WFCD name translation output for craftable parts (previously would've errored when new prime data comes into market sheet and/or WFCD data
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**
=> Add default cost for new no-stats items, fix translation layer for marketdata

WFInfo/Data.cs, WFInfo/Ocr.cs, WFInfo/Settings/ApplicationSettings.cs, WFInfo/Settings/IReadOnlyApplicationSettings.cs, WFInfo/Settings/SettingsViewModel.cs, WFInfo/Settings/SettingsWindow.xaml
(built on top of #249)
- Rewrote most of the core logic for snap-it item counting to accomodate the UI changes that happened in [update 31.1.0](https://forums.warframe.com/topic/1299619-update-3110-echoes-of-war/)
- Add separate display time setting for snap-it (reusing the now-deprecated snap noise UI elements)
- Removed settings deprecated by the snap-it item counting rewrite
---
1. Use snap-it
2. Start timer when first result pops in
3. Stop timer when first result pops out
4. Check if it follows the `Display Time` setting or the `Display Time (snap)` setting *(note: setting changes seem to only save once you move selection to a different setting, or toggle a checkbox or radio button)* 
---
Setting changes can be seen in the various settings subfolders, along with the line within …
=> Snapit item counting rewrite, Separate snap-it display time

WFInfo/EquipmentWindow.cs, WFInfo/RelicsViewModel.cs
Hard-coded a .5s (configurable) buffer in between the last change to the search and the final load, so that we weren't regenerating the search every single time.
"One is that some people were requesting searches in the various windows to only take effect when you press enter or similar, since the constant updates cause a fair bit of lag. "
---
---
https://gyazo.com/804e83bc2e6b2378afd819d5b89a46ab for gif of usage
- Does this contain a new dependency? **[No, but we are using a new library.]** In order to smoothly include for the situations in which multiple letters are being changed within the .5 second SLA, we are using a different timing class. Instead of using Windows.Threading.Timer, we are using Windows.Systems.Forms (https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.t …
=> Only running search after input is finished

WFInfo/Settings/ThemeAdjuster.xaml, WFInfo/Settings/ThemeAdjuster.xaml.cs, WFInfo/Templates/Styles.xaml
- Changed Scrollbar Colour
- Dimon thought the new settings from #263 were somewhat concealed due to the settings menu scrollbar blending in with the rest of the window. I think this colour change makes it sufficiently obvious without being too distracting
- If anyone has a better idea (or colour),  I'm open to suggestions
- ThemeAdjuster changes
- Add import/export functionality
- Add some tooltips
- Add basic instructions below image
- Images are immediately shown on load
---
1. Look at any window with a scrollbar
1.  Open Theme Adjuster
2. Adjust filters as desired, or leave them be
3. Click export button
4. Copy the contents of the textbox wherever you want
1.  Open Theme Adjuster
2. Paste an export into the textbox (or from other sources, as long as it has all required entries)
3. …
=> Scrollbar colour, Custom Theme import/export, ThemeAdjuster UI adjustments

WFInfo/Data.cs, WFInfo/Settings/ApplicationSettings.cs, WFInfo/Settings/IReadOnlyApplicationSettings.cs
- Auto-trigger now has a fixed delay if theme is manually selected
- This delay can be modified via the settings file, with the entry `FixedAutoDelay` (in milliseconds). I decided not to put it in the UI at this time, but if it turns out to frequently need adjustment I'll do that.
---
1. Enable Auto-trigger
2. Add some condition that'd make the best theme confidence below 40, for example colourblind mode
3. Select and tune custom theme for those conditions
- If the filter for one of the existing themes work, that's also applicable
4. Run a fissure, see if Auto-trigger works
---
[Fixed delay length can be found here](https://github.com/D1firehail/WFinfo/blob/99d1dad98cacc5b56b9fe1813e2871dfba9efb2d/WFInfo/Settings/ApplicationSettings.cs#L116). 2 seconds felt like an appropriate default, …
=> Fixed auto delay for manual theme selection (file-only setting)

WFInfo/Data.cs
Fixed issue where certain items would crash search-it
---
1. Start search-it
2. Search for `Baruuk Prime Chassis`
3. Without fix: freeze/crash. With fix: works as expected
---
It's in the one block of code that's been changed
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**
=> Fix Naive URL name approach

README.md, WFInfo/errorDialogue.xaml.cs
Discord changed it's max default upload size from a measly 8mb to a measly 25mb. This will slash the amount of zip files a user has to upload in third if the archive is large. Also a small change to the read-me with updated discord tag
---
N/A
---
N/A
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter? **No**
- Is is a bug fix, feature request, or enhancement? **Enhancement/Docs**
=> Max upload fix

WFInfo/Data.cs, WFInfo/Main.cs, WFInfo/Properties/AssemblyInfo.cs, WFInfo/WFInfo.csproj
* Fix proper fallback for pre-HDR sdk Win 10 builds
* Add WFM cache reuse if its down
* Bump version to new release 9.6.2
=> Bump version, fix win10 pre HDR sdk, add WFM cache reuse

WFInfo/Services/Screenshot/WindowsCaptureScreenshotService.cs
A copy of the screenshot texture (in windows capture) was not being freed after creating a bitmap for further processing. This led to shared GPU memory slowly running out until WFInfo would crash. This PR properly disposes of said texture.
=> Fix CPU-readable copy of screenshot texture not being disposed

WFInfo/Main.cs
WFMarket timeout detection only runs when the game is being streamed, but instead it should run when the game is **not** being streamed.
This fixes automatic WFMarket status updates not working for most users.
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Have I run the linter? **Yes**
- Is is a bug fix, feature request, or enhancement? **Bug Fix**
=> Fix WFMarket timeout streaming check

WFInfo/Settings/ApplicationSettings.cs
Fix Left/Right arrow keys being used as Activation Key also making Left/Right mouse keys being considered as Activation Key
---
1. Set the Left or RIght arrow keys as your activation key
2. Press Left or Right mouse key
---
- Is is a bug fix, feature request, or enhancement? **[Bug Fix**
=> Fix Left/Right arrow keys also being read as mouse keys

WFInfo/LowLevelListener.cs, WFInfo/Main.cs, WFInfo/Ocr.cs, WFInfo/Services/Screenshot/GdiScreenshotService.cs, WFInfo/Services/Screenshot/IScreenshotService.cs, WFInfo/Services/Screenshot/ImageScreenshotService.cs, WFInfo/Services/Screenshot/WindowsCaptureScreenshotService.cs, WFInfo/Services/WarframeProcess/WarframeProcessFinder.cs, WFInfo/Services/WindowInfo/Win32WindowInfoService.cs, WFInfo/Settings/SettingsViewModel.cs, WFInfo/Settings/SettingsWindow.xaml, WFInfo/Settings/SettingsWindow.xaml.cs
- Improve safeguard of theme selector setting. Previously, it gave a warning on closing dropdown. Now, it reacts on actual selection and gives an option to cancel.
- Bounce mouse and keyboard callbacks via Dispatcher InvokeAsync to prevent crash. Possibly specific to debug mode and/or game not running.
- Restore old behaviour of debug flag, making it grab entire primary screen if the game process is closed.
- Allow CaptureScreenshot method to fail, and add safeguards in case it fails. It could previously happen due to game closing mid-activation or by using snap-it or master-it with game closed and debug mode off.
- Does this pr include updated data files in a …
=> Improve theme selector safeguard, Restore Pre-HDR PR behaviour of debug setting
